# my global config
global:
  scrape_interval: 6s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 7s # Evaluate rules every 15 seconds. The default is every 1 minute.
 # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 10.107.128.31:9093
 
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
#   - alert_rules.yml
#   - rules.yml
#    - ssl.yml
    - http2.yml
    - icmp1.yml
#    - icmp.yml
    - ping_alerts.yml
#   - rules.yml
#    - http.yml
    - /etc/prometheus/jsonip/10.107.1.32.yml
    - /etc/prometheus/jsonip/10.107.1.35.yml
    - /etc/prometheus/jsonip/10.107.1.33.yml
    - linkup.yml
#   - linkdown.yml
# - "first_rules.yml"
  # - "second_rules.yml"






scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.107.128.31:9090']








###################################################ICMP##########################################################################################





###################################################ICMP##########################################################################################


###################################################SNMP##########################################################################################


  - job_name: '2A CC Aruba Instant On 1930 48G 4SFP/SFP+ Switch JL685A'
    static_configs:
      - targets:
          - 10.107.1.2
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)
   


  - job_name: '0C Media Aruba Instant On 1930 48G 4SFP/SFP+ Switch JL685A'
    static_configs:
      - targets:
          - 10.107.1.37
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)

  - job_name: '3A Aruba Instant On 1930 48G 4SFP/SFP+ Switch JL685A'
    static_configs:
      - targets:
          - 10.107.1.19
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)


  - job_name: '2C Upper HPE OfficeConnect Switch 1920S 48G 4SFP JL382A'
    static_configs:
      - targets:
          - 10.107.1.33
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)





  - job_name: 'HPE OfficeConnect Switch 1920S 48G 4SFP JL382A'
    static_configs:
      - targets:
          - 10.107.1.32
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)




  - job_name: '1A HPE OfficeConnect Switch 1920S 48G 4SFP JL382A'
    static_configs:
      - targets:
          - 10.107.1.35
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)
  




  - job_name: 'Fortigate1'
    static_configs:
      - targets:
          - 10.107.32.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)



  - job_name: 'Fortigate2'
    static_configs:
      - targets:
          - 10.107.1.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116
    scrape_interval: 1m   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 20s   # Тайм-аут запроса (по умолчанию 10 секунд)






  - job_name: 'AP'
    static_configs:
      - targets:
          - 10.107.12.37
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116






  - job_name: 'flask_api'
    static_configs:
      - targets: ['10.107.128.31:5002']


  - job_name: 'ping_metrics'
    static_configs:
      - targets: ['10.107.128.31:8000']   #u10.voip


  - job_name: 'ping_metrics1'
    static_configs:
      - targets: ['10.107.128.31:8001'] #m3.voip 




  - job_name: 'zabbix'  # Имя вашей задачи
    static_configs:
      - targets: ['10.107.128.31:9273'] # Замените на IP-адрес и порт вашего Telegraf




  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://glpi-office107.service-asdf.com
        - https://chat-office107.service-asdf.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9115
    scrape_interval: 22s   # Интервал опроса метрик (по умолчанию 1 минута)
    scrape_timeout: 21s   # Тайм-аут запроса (по умолчанию 10 секунд)





  - job_name: '1А-Middle'
    static_configs:
      - targets:
          - 10.107.12.12
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '1A-HR'
    static_configs:
      - targets:
          - 10.107.12.8
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '1A-MEDIA'
    static_configs:
      - targets:
          - 10.107.12.9
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2A-CC/1'
    static_configs:
      - targets:
          - 10.107.11.3
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2A-CC/2'
    static_configs:
      - targets:
          - 10.107.11.5
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2A-HR'
    static_configs:
      - targets:
          - 10.107.11.2
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2A-QC'
    static_configs:
      - targets:
          - 10.107.11.6
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2A-Support'
    static_configs:
      - targets:
          - 10.107.11.4
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2B-AF'
    static_configs:
      - targets:
          - 10.107.12.39
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2B-DEV'
    static_configs:
      - targets:
          - 10.107.12.36
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2B-Marketing'
    static_configs:
      - targets:
          - 10.107.12.3
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-HR'
    static_configs:
      - targets:
          - 10.107.12.2
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-NIK'
    static_configs:
      - targets:
          - 10.107.12.62
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-PAY'
    static_configs:
      - targets:
          - 10.107.12.22
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-PROD'
    static_configs:
      - targets:
          - 10.107.12.35
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-SEO'
    static_configs:
      - targets:
          - 10.107.12.37
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '2C-USW-Pro-48-PoE-Switch'
    static_configs:
      - targets:
          - 10.107.1.36
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '3A-EMAIL'
    static_configs:
      - targets:
          - 10.107.9.175
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '3A-PSP'
    static_configs:
      - targets:
          - 10.107.9.2
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: '3A-Mediaby'
    static_configs:
      - targets:
          - 10.107.12.49
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116

  - job_name: 'US-24-250W'
    static_configs:
      - targets:
          - 10.107.1.5
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.107.128.31:9116



 
